package org.rostore.entity;

/**
 * Base class for all exceptions generated by the RoStore core
 */
public class RoStoreException extends RuntimeException {

    /**
     * Create a RoStore expection
     * @param message error message
     */
    public RoStoreException(final String message) {
        super(message);
    }

    /**
     * Creates a RiStore exception
     * @param message error message
     * @param throwable the cause-exception
     */
    public RoStoreException(final String message, Throwable throwable) {
        super(message, throwable);
    }
}
