package org.rostore.entity;

/**
 * Base class for all exceptions generated by the RoStore core
 */
public class RoStoreException extends RuntimeException {

    /**
     * {@inheritDoc}
     */
    public RoStoreException(final String message) {
        super(message);
    }

    /**
     * {@inheritDoc}
     */
    public RoStoreException(final String message, Throwable throwable) {
        super(message, throwable);
    }
}
